// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: meshtastic/serial_hal.proto

package generated

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SerialHalCommand_Type int32

const (
	SerialHalCommand_UNSET            SerialHalCommand_Type = 0
	SerialHalCommand_PIN_MODE         SerialHalCommand_Type = 1
	SerialHalCommand_DIGITAL_WRITE    SerialHalCommand_Type = 2
	SerialHalCommand_DIGITAL_READ     SerialHalCommand_Type = 3
	SerialHalCommand_ATTACH_INTERRUPT SerialHalCommand_Type = 4
	SerialHalCommand_DETACH_INTERRUPT SerialHalCommand_Type = 5
	SerialHalCommand_SPI_TRANSFER     SerialHalCommand_Type = 6
	SerialHalCommand_NOOP             SerialHalCommand_Type = 7
)

// Enum value maps for SerialHalCommand_Type.
var (
	SerialHalCommand_Type_name = map[int32]string{
		0: "UNSET",
		1: "PIN_MODE",
		2: "DIGITAL_WRITE",
		3: "DIGITAL_READ",
		4: "ATTACH_INTERRUPT",
		5: "DETACH_INTERRUPT",
		6: "SPI_TRANSFER",
		7: "NOOP",
	}
	SerialHalCommand_Type_value = map[string]int32{
		"UNSET":            0,
		"PIN_MODE":         1,
		"DIGITAL_WRITE":    2,
		"DIGITAL_READ":     3,
		"ATTACH_INTERRUPT": 4,
		"DETACH_INTERRUPT": 5,
		"SPI_TRANSFER":     6,
		"NOOP":             7,
	}
)

func (x SerialHalCommand_Type) Enum() *SerialHalCommand_Type {
	p := new(SerialHalCommand_Type)
	*p = x
	return p
}

func (x SerialHalCommand_Type) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SerialHalCommand_Type) Descriptor() protoreflect.EnumDescriptor {
	return file_meshtastic_serial_hal_proto_enumTypes[0].Descriptor()
}

func (SerialHalCommand_Type) Type() protoreflect.EnumType {
	return &file_meshtastic_serial_hal_proto_enumTypes[0]
}

func (x SerialHalCommand_Type) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SerialHalCommand_Type.Descriptor instead.
func (SerialHalCommand_Type) EnumDescriptor() ([]byte, []int) {
	return file_meshtastic_serial_hal_proto_rawDescGZIP(), []int{0, 0}
}

type SerialHalResponse_Result int32

const (
	SerialHalResponse_OK          SerialHalResponse_Result = 0
	SerialHalResponse_ERROR       SerialHalResponse_Result = 1
	SerialHalResponse_BAD_REQUEST SerialHalResponse_Result = 2
	SerialHalResponse_UNSUPPORTED SerialHalResponse_Result = 3
)

// Enum value maps for SerialHalResponse_Result.
var (
	SerialHalResponse_Result_name = map[int32]string{
		0: "OK",
		1: "ERROR",
		2: "BAD_REQUEST",
		3: "UNSUPPORTED",
	}
	SerialHalResponse_Result_value = map[string]int32{
		"OK":          0,
		"ERROR":       1,
		"BAD_REQUEST": 2,
		"UNSUPPORTED": 3,
	}
)

func (x SerialHalResponse_Result) Enum() *SerialHalResponse_Result {
	p := new(SerialHalResponse_Result)
	*p = x
	return p
}

func (x SerialHalResponse_Result) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SerialHalResponse_Result) Descriptor() protoreflect.EnumDescriptor {
	return file_meshtastic_serial_hal_proto_enumTypes[1].Descriptor()
}

func (SerialHalResponse_Result) Type() protoreflect.EnumType {
	return &file_meshtastic_serial_hal_proto_enumTypes[1]
}

func (x SerialHalResponse_Result) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SerialHalResponse_Result.Descriptor instead.
func (SerialHalResponse_Result) EnumDescriptor() ([]byte, []int) {
	return file_meshtastic_serial_hal_proto_rawDescGZIP(), []int{1, 0}
}

type SerialHalCommand struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Host-assigned request id. Replies echo this id back in
	// SerialHalResponse.transaction_id.
	TransactionId uint32                `protobuf:"varint,1,opt,name=transaction_id,json=transactionId,proto3" json:"transaction_id,omitempty"`
	Type          SerialHalCommand_Type `protobuf:"varint,2,opt,name=type,proto3,enum=meshtastic.SerialHalCommand_Type" json:"type,omitempty"`
	Pin           uint32                `protobuf:"varint,3,opt,name=pin,proto3" json:"pin,omitempty"`
	Value         uint32                `protobuf:"varint,4,opt,name=value,proto3" json:"value,omitempty"`
	Mode          uint32                `protobuf:"varint,5,opt,name=mode,proto3" json:"mode,omitempty"`
	Data          []byte                `protobuf:"bytes,6,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SerialHalCommand) Reset() {
	*x = SerialHalCommand{}
	mi := &file_meshtastic_serial_hal_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SerialHalCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SerialHalCommand) ProtoMessage() {}

func (x *SerialHalCommand) ProtoReflect() protoreflect.Message {
	mi := &file_meshtastic_serial_hal_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SerialHalCommand.ProtoReflect.Descriptor instead.
func (*SerialHalCommand) Descriptor() ([]byte, []int) {
	return file_meshtastic_serial_hal_proto_rawDescGZIP(), []int{0}
}

func (x *SerialHalCommand) GetTransactionId() uint32 {
	if x != nil {
		return x.TransactionId
	}
	return 0
}

func (x *SerialHalCommand) GetType() SerialHalCommand_Type {
	if x != nil {
		return x.Type
	}
	return SerialHalCommand_UNSET
}

func (x *SerialHalCommand) GetPin() uint32 {
	if x != nil {
		return x.Pin
	}
	return 0
}

func (x *SerialHalCommand) GetValue() uint32 {
	if x != nil {
		return x.Value
	}
	return 0
}

func (x *SerialHalCommand) GetMode() uint32 {
	if x != nil {
		return x.Mode
	}
	return 0
}

func (x *SerialHalCommand) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type SerialHalResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Matches the originating SerialHalCommand.transaction_id for normal
	// request/response traffic.
	//
	// A value of 0 indicates an unsolicited interrupt notification generated by
	// the device. In that case, the host should interpret value as the GPIO pin
	// that triggered.
	TransactionId uint32                   `protobuf:"varint,1,opt,name=transaction_id,json=transactionId,proto3" json:"transaction_id,omitempty"`
	Result        SerialHalResponse_Result `protobuf:"varint,2,opt,name=result,proto3,enum=meshtastic.SerialHalResponse_Result" json:"result,omitempty"`
	// Used by DIGITAL_READ replies and interrupt notifications. For interrupt
	// notifications (transaction_id == 0), this carries the pin number.
	Value         uint32 `protobuf:"varint,3,opt,name=value,proto3" json:"value,omitempty"`
	Data          []byte `protobuf:"bytes,4,opt,name=data,proto3" json:"data,omitempty"`
	Error         string `protobuf:"bytes,5,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SerialHalResponse) Reset() {
	*x = SerialHalResponse{}
	mi := &file_meshtastic_serial_hal_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SerialHalResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SerialHalResponse) ProtoMessage() {}

func (x *SerialHalResponse) ProtoReflect() protoreflect.Message {
	mi := &file_meshtastic_serial_hal_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SerialHalResponse.ProtoReflect.Descriptor instead.
func (*SerialHalResponse) Descriptor() ([]byte, []int) {
	return file_meshtastic_serial_hal_proto_rawDescGZIP(), []int{1}
}

func (x *SerialHalResponse) GetTransactionId() uint32 {
	if x != nil {
		return x.TransactionId
	}
	return 0
}

func (x *SerialHalResponse) GetResult() SerialHalResponse_Result {
	if x != nil {
		return x.Result
	}
	return SerialHalResponse_OK
}

func (x *SerialHalResponse) GetValue() uint32 {
	if x != nil {
		return x.Value
	}
	return 0
}

func (x *SerialHalResponse) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *SerialHalResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

var File_meshtastic_serial_hal_proto protoreflect.FileDescriptor

const file_meshtastic_serial_hal_proto_rawDesc = "" +
	"\n" +
	"\x1bmeshtastic/serial_hal.proto\x12\n" +
	"meshtastic\"\xcf\x02\n" +
	"\x10SerialHalCommand\x12%\n" +
	"\x0etransaction_id\x18\x01 \x01(\rR\rtransactionId\x125\n" +
	"\x04type\x18\x02 \x01(\x0e2!.meshtastic.SerialHalCommand.TypeR\x04type\x12\x10\n" +
	"\x03pin\x18\x03 \x01(\rR\x03pin\x12\x14\n" +
	"\x05value\x18\x04 \x01(\rR\x05value\x12\x12\n" +
	"\x04mode\x18\x05 \x01(\rR\x04mode\x12\x12\n" +
	"\x04data\x18\x06 \x01(\fR\x04data\"\x8c\x01\n" +
	"\x04Type\x12\t\n" +
	"\x05UNSET\x10\x00\x12\f\n" +
	"\bPIN_MODE\x10\x01\x12\x11\n" +
	"\rDIGITAL_WRITE\x10\x02\x12\x10\n" +
	"\fDIGITAL_READ\x10\x03\x12\x14\n" +
	"\x10ATTACH_INTERRUPT\x10\x04\x12\x14\n" +
	"\x10DETACH_INTERRUPT\x10\x05\x12\x10\n" +
	"\fSPI_TRANSFER\x10\x06\x12\b\n" +
	"\x04NOOP\x10\a\"\xf7\x01\n" +
	"\x11SerialHalResponse\x12%\n" +
	"\x0etransaction_id\x18\x01 \x01(\rR\rtransactionId\x12<\n" +
	"\x06result\x18\x02 \x01(\x0e2$.meshtastic.SerialHalResponse.ResultR\x06result\x12\x14\n" +
	"\x05value\x18\x03 \x01(\rR\x05value\x12\x12\n" +
	"\x04data\x18\x04 \x01(\fR\x04data\x12\x14\n" +
	"\x05error\x18\x05 \x01(\tR\x05error\"=\n" +
	"\x06Result\x12\x06\n" +
	"\x02OK\x10\x00\x12\t\n" +
	"\x05ERROR\x10\x01\x12\x0f\n" +
	"\vBAD_REQUEST\x10\x02\x12\x0f\n" +
	"\vUNSUPPORTED\x10\x03B_\n" +
	"\x14org.meshtastic.protoB\tSerialHalZ\"github.com/meshtastic/go/generated\xaa\x02\x14Meshtastic.Protobufs\xba\x02\x00b\x06proto3"

var (
	file_meshtastic_serial_hal_proto_rawDescOnce sync.Once
	file_meshtastic_serial_hal_proto_rawDescData []byte
)

func file_meshtastic_serial_hal_proto_rawDescGZIP() []byte {
	file_meshtastic_serial_hal_proto_rawDescOnce.Do(func() {
		file_meshtastic_serial_hal_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_meshtastic_serial_hal_proto_rawDesc), len(file_meshtastic_serial_hal_proto_rawDesc)))
	})
	return file_meshtastic_serial_hal_proto_rawDescData
}

var file_meshtastic_serial_hal_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_meshtastic_serial_hal_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_meshtastic_serial_hal_proto_goTypes = []any{
	(SerialHalCommand_Type)(0),    // 0: meshtastic.SerialHalCommand.Type
	(SerialHalResponse_Result)(0), // 1: meshtastic.SerialHalResponse.Result
	(*SerialHalCommand)(nil),      // 2: meshtastic.SerialHalCommand
	(*SerialHalResponse)(nil),     // 3: meshtastic.SerialHalResponse
}
var file_meshtastic_serial_hal_proto_depIdxs = []int32{
	0, // 0: meshtastic.SerialHalCommand.type:type_name -> meshtastic.SerialHalCommand.Type
	1, // 1: meshtastic.SerialHalResponse.result:type_name -> meshtastic.SerialHalResponse.Result
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_meshtastic_serial_hal_proto_init() }
func file_meshtastic_serial_hal_proto_init() {
	if File_meshtastic_serial_hal_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_meshtastic_serial_hal_proto_rawDesc), len(file_meshtastic_serial_hal_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_meshtastic_serial_hal_proto_goTypes,
		DependencyIndexes: file_meshtastic_serial_hal_proto_depIdxs,
		EnumInfos:         file_meshtastic_serial_hal_proto_enumTypes,
		MessageInfos:      file_meshtastic_serial_hal_proto_msgTypes,
	}.Build()
	File_meshtastic_serial_hal_proto = out.File
	file_meshtastic_serial_hal_proto_goTypes = nil
	file_meshtastic_serial_hal_proto_depIdxs = nil
}
